language: ruby
rvm:
- 2.1.1
before_install:
- git config --global user.email "vasilescu@gmail.com"
- git config --global user.name "Bogdan Vasilescu"
install:
- bundle install
branches:
  only:
  - develop
script:
- bundle exec rake deploy
notifications:
  email: false
env:
  global:
    secure: XtkU0DJnXKQWFdeqxpRu0SddvbRFnfZYGy3C8wl4ubVp9dNQ+/ND7w70WSNoUhTyXUHEdDCNKEVkKZH7xvEQQXuNuYMtFbieS0f6ODSO6ZQ4WYSLxHeduKi0T+AsSDSKISfhInRv+VGrjKWYKKjXMZuVPFHFGsy1Rx97eQ2ASK+Xr8Hv8jIUG2DlF4/CKDBN9dhWXZi7yi8TieKDSfwDAueFlQWo8CyyItUfJGqvL9Hptjy9oEHAaTQ9SbCG8jgLJp/ysFgAq5feMgZJHGgeZz3f3OaJASfizlKfN1Hy5k4N8m3r+ZR0d3I4hNGCb5+SyPFv+nrAYggarcnmLXi7SUMo0KOh3EBGlP1KwGiahin2oKmMA9tm1Mcn+Crx7OH2H/+rpsjhd0jZeVB2flyQr2/aSJf1pT0Km1/Ra36VO5cktsrWPF16zGx5ZwPhDcCBfqtJTDODW77aeWpKaltALEN9Fprv4mIpltPWSEotwCPcb1m4A81MDFdJxQJxOkeeWedNo6vPbbEkxGtvVreZxVzuwltqlJa2ucf1jlULKs26bJj62E8lP19sh1y5clp6ZmcLQ8URWw717VxmrFp0oOTBiga+QXy/I6OWiYPYhJn4I9DLP9+CkGfzo8OCwlQilNhUCJGCndoLJwZPHBI7nlgiN8NrDvCLKKMtEehWaKA=
